# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_NAME=winddev_db
      - POSTGRES_USER=winddev_user
      - POSTGRES_PASSWORD=winddev_password
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # dbサービスが起動してからwebサービスを起動するように設定
    depends_on:
      - db

  db:
    # PostgreSQLの公式イメージを使用
    image: postgres:15
    volumes:
      # DBのデータを永続化するためにローカルに保存
      - postgres_data:/var/lib/postgresql/data/
    # DBの環境変数を設定（上記webサービスの環境変数と合わせる）
    environment:
      - POSTGRES_DB=winddev_db
      - POSTGRES_USER=winddev_user
      - POSTGRES_PASSWORD=winddev_password

volumes:
  postgres_data: