# Generated by Django 4.2.11 on 2025-09-01 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DISPATCH', 'Dispatch Report'), ('WIND', 'Wind Report')], default='WIND', max_length=10)),
                ('work_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('close_number', models.IntegerField()),
                ('swing_number', models.IntegerField()),
                ('new_close_number', models.IntegerField(blank=True, null=True)),
                ('upg_close_number', models.IntegerField(blank=True, null=True)),
                ('mnp_close_number', models.IntegerField(blank=True, null=True)),
                ('tv_close_number', models.IntegerField(blank=True, null=True)),
                ('net_close_number', models.IntegerField(blank=True, null=True)),
                ('tel_close_number', models.IntegerField(blank=True, null=True)),
                ('tos_close_number', models.IntegerField(blank=True, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_img', models.ImageField(upload_to='report_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.report')),
            ],
        ),
    ]
