# Generated by Django 4.2.11 on 2025-09-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='clock_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
