# Generated by Django 4.2.11 on 2025-08-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_id', models.IntegerField()),
                ('carrier_name', models.CharField(max_length=100)),
            ],
        ),
    ]
