# Generated by Django 4.2.11 on 2025-08-25 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wind_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DISPATCH', 'Dispatch Report'), ('WIND', 'Wind Report')], default='WIND', max_length=10)),
                ('work_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('close_number', models.IntegerField()),
                ('swing_number', models.IntegerField()),
                ('new_close_number', models.IntegerField(blank=True, null=True)),
                ('upg_close_number', models.IntegerField(blank=True, null=True)),
                ('mnp_close_number', models.IntegerField(blank=True, null=True)),
                ('tv_close_number', models.IntegerField(blank=True, null=True)),
                ('net_close_number', models.IntegerField(blank=True, null=True)),
                ('tel_close_number', models.IntegerField(blank=True, null=True)),
                ('tos_close_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='carrier_id',
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_img', models.ImageField(upload_to='report_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wind_app.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wind_app.carrier'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
